### ISSUE TITLE
Bordure pour afficher la section courante

### ISSUE THREAD

**Issue by Bludwarf** [Bludwarf/music-diagram-generator#18]
Exemple : 

![image](https://github.com/Bludwarf/music-diagram-generator/assets/6860189/60fae5f1-4d06-43e3-be44-8a994059854f)

![image](https://github.com/Bludwarf/music-diagram-generator/assets/6860189/f9bd7231-a939-4880-bb6d-0e3f3287bed7)

ou

![image](https://github.com/Bludwarf/music-diagram-generator/assets/6860189/49ae7a2a-a319-4d21-9327-ff0c94c736f6)

ou juste

![image](https://github.com/Bludwarf/music-diagram-generator/assets/6860189/ab72fa78-d353-464b-a3d9-07ac47ed20f8)

ou avec :

```css
element.style {
    box-shadow: 0 0px 20px black;
    clip-path: inset(-30px -30px 0px -30px);
    border-top-left-radius: 0.2rem;
    border-top-right-radius: 0.2rem;
}
```

![image](https://github.com/Bludwarf/music-diagram-generator/assets/6860189/5a56f3f4-35dc-4a0a-b20a-d5ce8eabf6b8)
